/// <reference types="nativewind/types" />
/// <reference types="nativewind/types" />

declare module "*.css";

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.